'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        '''<summary>
        '''Installed location of the Nightscape Client.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Installed location of the Nightscape Client."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property NightscapeLocation() As String
            Get
                Return CType(Me("NightscapeLocation"),String)
            End Get
            Set
                Me("NightscapeLocation") = value
            End Set
        End Property
        
        '''<summary>
        '''Installed location of InsideUO
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Installed location of InsideUO"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property InsideUOLocation() As String
            Get
                Return CType(Me("InsideUOLocation"),String)
            End Get
            Set
                Me("InsideUOLocation") = value
            End Set
        End Property
        
        '''<summary>
        '''Tobbles tooltip style between standard and balloon.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Tobbles tooltip style between standard and balloon."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("standard")>  _
        Public Property TooltipStyle() As String
            Get
                Return CType(Me("TooltipStyle"),String)
            End Get
            Set
                Me("TooltipStyle") = value
            End Set
        End Property
        
        '''<summary>
        '''Tab to show when the program first starts.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Tab to show when the program first starts."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property StartupTab() As String
            Get
                Return CType(Me("StartupTab"),String)
            End Get
            Set
                Me("StartupTab") = value
            End Set
        End Property
        
        '''<summary>
        '''Toggles between launch the patch client or the game client directly.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Toggles between launch the patch client or the game client directly."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("patch")>  _
        Public Property AutoLaunchType() As String
            Get
                Return CType(Me("AutoLaunchType"),String)
            End Get
            Set
                Me("AutoLaunchType") = value
            End Set
        End Property
        
        '''<summary>
        '''Specifies the icon to use in the system tray.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Specifies the icon to use in the system tray."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SystrayIcon() As String
            Get
                Return CType(Me("SystrayIcon"),String)
            End Get
            Set
                Me("SystrayIcon") = value
            End Set
        End Property
        
        '''<summary>
        '''Toggles between always showing the program on the taskbar and only showingit when maximized.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Toggles between always showing the program on the taskbar and only showingit when"& _ 
            " maximized."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("always")>  _
        Public Property TaskbarType() As String
            Get
                Return CType(Me("TaskbarType"),String)
            End Get
            Set
                Me("TaskbarType") = value
            End Set
        End Property
        
        '''<summary>
        '''Type of opacity feature to use.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Type of opacity feature to use."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("onfocus")>  _
        Public Property Opacity() As String
            Get
                Return CType(Me("Opacity"),String)
            End Get
            Set
                Me("Opacity") = value
            End Set
        End Property
        
        '''<summary>
        '''Appear on top of other programs
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Appear on top of other programs"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AlwaysOnTop() As Boolean
            Get
                Return CType(Me("AlwaysOnTop"),Boolean)
            End Get
            Set
                Me("AlwaysOnTop") = value
            End Set
        End Property
        
        '''<summary>
        '''Enable or disable tooltips for the program.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enable or disable tooltips for the program."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableTooltips() As Boolean
            Get
                Return CType(Me("EnableTooltips"),Boolean)
            End Get
            Set
                Me("EnableTooltips") = value
            End Set
        End Property
        
        '''<summary>
        '''Enable or disable showing the splash screen when the program starts.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enable or disable showing the splash screen when the program starts."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowSplashScreen() As Boolean
            Get
                Return CType(Me("ShowSplashScreen"),Boolean)
            End Get
            Set
                Me("ShowSplashScreen") = value
            End Set
        End Property
        
        '''<summary>
        '''Enable or disable auto-launching the Nightscape client when the program starts.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enable or disable auto-launching the Nightscape client when the program starts."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutoLaunchClient() As Boolean
            Get
                Return CType(Me("AutoLaunchClient"),Boolean)
            End Get
            Set
                Me("AutoLaunchClient") = value
            End Set
        End Property
        
        '''<summary>
        '''Enables or disables showing the program in the system tray.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enables or disables showing the program in the system tray."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowInTray() As Boolean
            Get
                Return CType(Me("ShowInTray"),Boolean)
            End Get
            Set
                Me("ShowInTray") = value
            End Set
        End Property
        
        '''<summary>
        '''Enables or disables showing the program on the taskbar.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enables or disables showing the program on the taskbar."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowOnTaskbar() As Boolean
            Get
                Return CType(Me("ShowOnTaskbar"),Boolean)
            End Get
            Set
                Me("ShowOnTaskbar") = value
            End Set
        End Property
        
        '''<summary>
        '''The level of opacity for the program.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("The level of opacity for the program."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property OpacityLevel() As Integer
            Get
                Return CType(Me("OpacityLevel"),Integer)
            End Get
            Set
                Me("OpacityLevel") = value
            End Set
        End Property
        
        '''<summary>
        '''Time in millliseconds for the program to return to opaque after regaining focus.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Time in millliseconds for the program to return to opaque after regaining focus."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("250")>  _
        Public Property FadeInTime() As Integer
            Get
                Return CType(Me("FadeInTime"),Integer)
            End Get
            Set
                Me("FadeInTime") = value
            End Set
        End Property
        
        '''<summary>
        '''Time in milliseconds for the program to face out to the desired transparency level after losing focus.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Time in milliseconds for the program to face out to the desired transparency leve"& _ 
            "l after losing focus."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("500")>  _
        Public Property FadeOutTime() As Integer
            Get
                Return CType(Me("FadeOutTime"),Integer)
            End Get
            Set
                Me("FadeOutTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_TeleTo() As Boolean
            Get
                Return CType(Me("QC_TeleTo"),Boolean)
            End Get
            Set
                Me("QC_TeleTo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_MTele() As Boolean
            Get
                Return CType(Me("QC_MTele"),Boolean)
            End Get
            Set
                Me("QC_MTele") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_GetInfo() As Boolean
            Get
                Return CType(Me("QC_GetInfo"),Boolean)
            End Get
            Set
                Me("QC_GetInfo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_Kill() As Boolean
            Get
                Return CType(Me("QC_Kill"),Boolean)
            End Get
            Set
                Me("QC_Kill") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_Ressurect() As Boolean
            Get
                Return CType(Me("QC_Ressurect"),Boolean)
            End Get
            Set
                Me("QC_Ressurect") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_Jail() As Boolean
            Get
                Return CType(Me("QC_Jail"),Boolean)
            End Get
            Set
                Me("QC_Jail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_Kick() As Boolean
            Get
                Return CType(Me("QC_Kick"),Boolean)
            End Get
            Set
                Me("QC_Kick") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_Hide() As Boolean
            Get
                Return CType(Me("QC_Hide"),Boolean)
            End Get
            Set
                Me("QC_Hide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_Destroy() As Boolean
            Get
                Return CType(Me("QC_Destroy"),Boolean)
            End Get
            Set
                Me("QC_Destroy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_MDestroy() As Boolean
            Get
                Return CType(Me("QC_MDestroy"),Boolean)
            End Get
            Set
                Me("QC_MDestroy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_RoofCreator() As Boolean
            Get
                Return CType(Me("QC_RoofCreator"),Boolean)
            End Get
            Set
                Me("QC_RoofCreator") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_ItemInfo() As Boolean
            Get
                Return CType(Me("QC_ItemInfo"),Boolean)
            End Get
            Set
                Me("QC_ItemInfo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_LockItem() As Boolean
            Get
                Return CType(Me("QC_LockItem"),Boolean)
            End Get
            Set
                Me("QC_LockItem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_Lockdown5() As Boolean
            Get
                Return CType(Me("QC_Lockdown5"),Boolean)
            End Get
            Set
                Me("QC_Lockdown5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_Lockdown10() As Boolean
            Get
                Return CType(Me("QC_Lockdown10"),Boolean)
            End Get
            Set
                Me("QC_Lockdown10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_ConcealMe() As Boolean
            Get
                Return CType(Me("QC_ConcealMe"),Boolean)
            End Get
            Set
                Me("QC_ConcealMe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_RevealMe() As Boolean
            Get
                Return CType(Me("QC_RevealMe"),Boolean)
            End Get
            Set
                Me("QC_RevealMe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_GMForm() As Boolean
            Get
                Return CType(Me("QC_GMForm"),Boolean)
            End Get
            Set
                Me("QC_GMForm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_MyForm() As Boolean
            Get
                Return CType(Me("QC_MyForm"),Boolean)
            End Get
            Set
                Me("QC_MyForm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_SaveShard() As Boolean
            Get
                Return CType(Me("QC_SaveShard"),Boolean)
            End Get
            Set
                Me("QC_SaveShard") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_Nightsight() As Boolean
            Get
                Return CType(Me("QC_Nightsight"),Boolean)
            End Get
            Set
                Me("QC_Nightsight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_HelpQueue() As Boolean
            Get
                Return CType(Me("QC_HelpQueue"),Boolean)
            End Get
            Set
                Me("QC_HelpQueue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_PropEdit() As Boolean
            Get
                Return CType(Me("QC_PropEdit"),Boolean)
            End Get
            Set
                Me("QC_PropEdit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_Mark() As Boolean
            Get
                Return CType(Me("QC_Mark"),Boolean)
            End Get
            Set
                Me("QC_Mark") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_Recall() As Boolean
            Get
                Return CType(Me("QC_Recall"),Boolean)
            End Get
            Set
                Me("QC_Recall") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_Where() As Boolean
            Get
                Return CType(Me("QC_Where"),Boolean)
            End Get
            Set
                Me("QC_Where") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_Goto() As Boolean
            Get
                Return CType(Me("QC_Goto"),Boolean)
            End Get
            Set
                Me("QC_Goto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property QC_SummonPlayer() As Boolean
            Get
                Return CType(Me("QC_SummonPlayer"),Boolean)
            End Get
            Set
                Me("QC_SummonPlayer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property QC_Tele() As Boolean
            Get
                Return CType(Me("QC_Tele"),Boolean)
            End Get
            Set
                Me("QC_Tele") = value
            End Set
        End Property
        
        '''<summary>
        '''Enable or disable automatically checking for software updates at startup.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enable or disable automatically checking for software updates at startup."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CheckUpdates() As Boolean
            Get
                Return CType(Me("CheckUpdates"),Boolean)
            End Get
            Set
                Me("CheckUpdates") = value
            End Set
        End Property
        
        '''<summary>
        '''How often to check for updates, can be &quot;always&quot;, &quot;daily&quot; or &quot;weekly&quot;.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("How often to check for updates, can be ""always"", ""daily"" or ""weekly""."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("daily")>  _
        Public Property UpdateInterval() As String
            Get
                Return CType(Me("UpdateInterval"),String)
            End Get
            Set
                Me("UpdateInterval") = value
            End Set
        End Property
        
        '''<summary>
        '''Date and time the last update check was performed.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Date and time the last update check was performed."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LastUpdateCheck() As Date
            Get
                Return CType(Me("LastUpdateCheck"),Date)
            End Get
            Set
                Me("LastUpdateCheck") = value
            End Set
        End Property
        
        '''<summary>
        '''Enable or disable automatically downloading and installing updates for the core executable.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enable or disable automatically downloading and installing updates for the core e"& _ 
            "xecutable."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UpdateCore() As Boolean
            Get
                Return CType(Me("UpdateCore"),Boolean)
            End Get
            Set
                Me("UpdateCore") = value
            End Set
        End Property
        
        '''<summary>
        '''Enable or disable automatically downloading and installing updates for the build list.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enable or disable automatically downloading and installing updates for the build "& _ 
            "list."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UpdateBuildList() As Boolean
            Get
                Return CType(Me("UpdateBuildList"),Boolean)
            End Get
            Set
                Me("UpdateBuildList") = value
            End Set
        End Property
        
        '''<summary>
        '''Enable or disable automatically downloading and installing updates for the item list.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enable or disable automatically downloading and installing updates for the item l"& _ 
            "ist."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UpdateItemList() As Boolean
            Get
                Return CType(Me("UpdateItemList"),Boolean)
            End Get
            Set
                Me("UpdateItemList") = value
            End Set
        End Property
        
        '''<summary>
        '''Enable or disable automatically downloading and installing updates for the NPC list.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enable or disable automatically downloading and installing updates for the NPC li"& _ 
            "st."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UpdateNPCList() As Boolean
            Get
                Return CType(Me("UpdateNPCList"),Boolean)
            End Get
            Set
                Me("UpdateNPCList") = value
            End Set
        End Property
        
        '''<summary>
        '''Enable or disable automatically downloading and installing updates for the travel list.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enable or disable automatically downloading and installing updates for the travel"& _ 
            " list."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UpdateLocationList() As Boolean
            Get
                Return CType(Me("UpdateLocationList"),Boolean)
            End Get
            Set
                Me("UpdateLocationList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Font() As Boolean
            Get
                Return CType(Me("Font"),Boolean)
            End Get
            Set
                Me("Font") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0.0.0")>  _
        Public Property CoreVersion() As String
            Get
                Return CType(Me("CoreVersion"),String)
            End Get
            Set
                Me("CoreVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0.0.0")>  _
        Public Property BuildListVersion() As String
            Get
                Return CType(Me("BuildListVersion"),String)
            End Get
            Set
                Me("BuildListVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0.0.0")>  _
        Public Property ItemListVersion() As String
            Get
                Return CType(Me("ItemListVersion"),String)
            End Get
            Set
                Me("ItemListVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0.0.0")>  _
        Public Property NPCListVersion() As String
            Get
                Return CType(Me("NPCListVersion"),String)
            End Get
            Set
                Me("NPCListVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0.0.0")>  _
        Public Property LocationListVersion() As String
            Get
                Return CType(Me("LocationListVersion"),String)
            End Get
            Set
                Me("LocationListVersion") = value
            End Set
        End Property
        
        '''<summary>
        '''Enable or disable autocomplete for certain form elements.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enable or disable autocomplete for certain form elements."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutoComplete() As Boolean
            Get
                Return CType(Me("AutoComplete"),Boolean)
            End Get
            Set
                Me("AutoComplete") = value
            End Set
        End Property
        
        '''<summary>
        '''Enable or disable showing NPCs animated in the preview window.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enable or disable showing NPCs animated in the preview window."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AnimateNPCs() As Boolean
            Get
                Return CType(Me("AnimateNPCs"),Boolean)
            End Get
            Set
                Me("AnimateNPCs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SearchByID1_AutoComplete() As Global.System.Windows.Forms.AutoCompleteStringCollection
            Get
                Return CType(Me("SearchByID1_AutoComplete"),Global.System.Windows.Forms.AutoCompleteStringCollection)
            End Get
            Set
                Me("SearchByID1_AutoComplete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SearchByName2_AutoComplete() As Global.System.Windows.Forms.AutoCompleteStringCollection
            Get
                Return CType(Me("SearchByName2_AutoComplete"),Global.System.Windows.Forms.AutoCompleteStringCollection)
            End Get
            Set
                Me("SearchByName2_AutoComplete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SearchByID2_AutoComplete() As Global.System.Windows.Forms.AutoCompleteStringCollection
            Get
                Return CType(Me("SearchByID2_AutoComplete"),Global.System.Windows.Forms.AutoCompleteStringCollection)
            End Get
            Set
                Me("SearchByID2_AutoComplete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property BCastMessage_AutoComplete() As Global.System.Windows.Forms.AutoCompleteStringCollection
            Get
                Return CType(Me("BCastMessage_AutoComplete"),Global.System.Windows.Forms.AutoCompleteStringCollection)
            End Get
            Set
                Me("BCastMessage_AutoComplete") = value
            End Set
        End Property
        
        '''<summary>
        '''Enable or disable the tracking of the in-game location.
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Enable or disable the tracking of the in-game location."),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TrackLocation() As Boolean
            Get
                Return CType(Me("TrackLocation"),Boolean)
            End Get
            Set
                Me("TrackLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserLaunch1_Name() As String
            Get
                Return CType(Me("UserLaunch1_Name"),String)
            End Get
            Set
                Me("UserLaunch1_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserLaunch1_Program() As String
            Get
                Return CType(Me("UserLaunch1_Program"),String)
            End Get
            Set
                Me("UserLaunch1_Program") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserLaunch1_Location() As String
            Get
                Return CType(Me("UserLaunch1_Location"),String)
            End Get
            Set
                Me("UserLaunch1_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property USerLaunch2_Name() As String
            Get
                Return CType(Me("USerLaunch2_Name"),String)
            End Get
            Set
                Me("USerLaunch2_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserLaunch2_Program() As String
            Get
                Return CType(Me("UserLaunch2_Program"),String)
            End Get
            Set
                Me("UserLaunch2_Program") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserLaunch2_Location() As String
            Get
                Return CType(Me("UserLaunch2_Location"),String)
            End Get
            Set
                Me("UserLaunch2_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserLaunch3_Name() As String
            Get
                Return CType(Me("UserLaunch3_Name"),String)
            End Get
            Set
                Me("UserLaunch3_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserLaunch3_Program() As String
            Get
                Return CType(Me("UserLaunch3_Program"),String)
            End Get
            Set
                Me("UserLaunch3_Program") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserLaunch3_Location() As String
            Get
                Return CType(Me("UserLaunch3_Location"),String)
            End Get
            Set
                Me("UserLaunch3_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserLaunch4_Name() As String
            Get
                Return CType(Me("UserLaunch4_Name"),String)
            End Get
            Set
                Me("UserLaunch4_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserLaunch4_Program() As String
            Get
                Return CType(Me("UserLaunch4_Program"),String)
            End Get
            Set
                Me("UserLaunch4_Program") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserLaunch4_Location() As String
            Get
                Return CType(Me("UserLaunch4_Location"),String)
            End Get
            Set
                Me("UserLaunch4_Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SearchByName3_AutoComplete() As Global.System.Windows.Forms.AutoCompleteStringCollection
            Get
                Return CType(Me("SearchByName3_AutoComplete"),Global.System.Windows.Forms.AutoCompleteStringCollection)
            End Get
            Set
                Me("SearchByName3_AutoComplete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SearchByName4_AutoComplete() As Global.System.Windows.Forms.AutoCompleteStringCollection
            Get
                Return CType(Me("SearchByName4_AutoComplete"),Global.System.Windows.Forms.AutoCompleteStringCollection)
            End Get
            Set
                Me("SearchByName4_AutoComplete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property FormLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("FormLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("FormLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RetainInput() As Boolean
            Get
                Return CType(Me("RetainInput"),Boolean)
            End Get
            Set
                Me("RetainInput") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SearchByName1_AutoComplete() As Global.System.Windows.Forms.AutoCompleteStringCollection
            Get
                Return CType(Me("SearchByName1_AutoComplete"),Global.System.Windows.Forms.AutoCompleteStringCollection)
            End Get
            Set
                Me("SearchByName1_AutoComplete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowBuildingToolbar() As Boolean
            Get
                Return CType(Me("ShowBuildingToolbar"),Boolean)
            End Get
            Set
                Me("ShowBuildingToolbar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property BuildingToolbarLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("BuildingToolbarLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("BuildingToolbarLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property RenderingQuality() As String
            Get
                Return CType(Me("RenderingQuality"),String)
            End Get
            Set
                Me("RenderingQuality") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Nightscape_Staff_Assistant.My.MySettings
            Get
                Return Global.Nightscape_Staff_Assistant.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
